apiVersion: v1
kind: Service
metadata:
  name: dzq-service-{{site_id}}	
  labels:     	
    app: dzq-{{site_id}}
spec:	    
  selector:	   
    app: dzq-{{site_id}}	
  ports:
  - name: dzq-port-{{site_id}}	
    #protocol: TCP	    
    port: 80	        
    #nodePort: 32600   
    targetPort: 80	
  type: NodePort
---
apiVersion: apps/v1	
kind: Deployment	
metadata:	        
  name: dzq-deployment-{{site_id}}	
  labels:	    
    app: dzq-{{site_id}}
  #namespace: ingress-nginx	
spec:	        
  replicas: 1	
  selector:	   
    matchLabels: 
      app: dzq-{{site_id}}
  template:	    
    metadata:	
      labels:	
        app: dzq-{{site_id}}
    spec:	    
      containers:
      - name: php-nginx
        ports:
        - containerPort: 80
        image: ccr.ccs.tencentyun.com/learnspaces/dzq-nginx-php:v1.0
      - name: mysql
        ports:
        - containerPort: 3306
        image: ccr.ccs.tencentyun.com/learnspaces/dzq-mysql:v1.0
        args: ["--character-set-server", "utf8mb4", "--collation-server", "utf8mb4_unicode_ci", "--default-authentication-plugin", "mysql_native_password"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root

