apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-admin-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: demo-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: frontend-admin-service-account
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: touch-frontend-service
  namespace: default	
  labels:     	
    app: touch-frontend
spec:	    
  selector:	   
    app: touch-frontend	
  ports:
  - name: touch-frontend-port	
    #protocol: TCP	    
    port: 80	        
    #nodePort: 32600   
    targetPort: 80	
  type: NodePort
---
apiVersion: apps/v1	
kind: Deployment	
metadata:	        
  name: touch-frontend-deployment
  namespace: default	
  labels:	    
    app: touch-frontend
spec:	        
  replicas: 1	
  selector:	   
    matchLabels: 
      app: touch-frontend
  template:	    
    metadata:	
      labels:	
        app: touch-frontend
    spec:	    
      serviceAccountName: frontend-admin-service-account
      containers:
      - name: php-nginx
        ports:
        - containerPort: 80
        image: ccr.ccs.tencentyun.com/learnspaces/frontend-nginx-php:v1.0
        imagePullPolicy: Always
      - name: mysql
        ports:
        - containerPort: 3306
        image: ccr.ccs.tencentyun.com/learnspaces/dzx-mysql:v1.0
        args: ["--character-set-server", "utf8mb4", "--collation-server", "utf8mb4_unicode_ci", "--default-authentication-plugin", "mysql_native_password"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: local-touch-ingress
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#spec:
#  rules:
#  - host: frontend.touch.com
#    http:
#      paths:
#      - backend:
#          serviceName: touch-frontend-service
#          servicePort: 80
